version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: skladisce_server
    restart: unless-stopped
    ports:
      - "2808:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: skavtisozakon
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
